# This is a generated file. Not intended for manual editing.
services:
  BddExample:
    build:
      context: "C:\\gmsl\\bdd-example"
      dockerfile: "src/Service/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Service.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "service:dev"
    ports: []
    volumes:
    - "C:\\Users\\benjamin.titmus\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\gmsl\\bdd-example\\src\\Service:/app:rw"
    - "C:\\gmsl\\bdd-example:/src:rw"
    working_dir: "/app"
