global using Api;
global using DotNet.Testcontainers.Builders;
global using DotNet.Testcontainers.Configurations;
global using DotNet.Testcontainers.Containers;
global using DotNet.Testcontainers.Images;
global using Logic.Interfaces;
global using NSubstitute;
global using Service;
global using Specs.Drivers;